apiVersion: apps/v1
kind: Deployment

metadata:
  name: spring-deployment

# Deployment 세부 정보
spec:
  replicas: 3
  selector:
    matchLabels:
      # 배포할 Pod 지정
      app: backend-app

  # 배포할 Pod 정의
  template:
    metadata:
      # 카테고리 개념
      labels:
        app: backend-app
    spec:
      # container 정보
      containers:
        - name: spring-container
          image: spring-server
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
